from views import auth_view
from views import dashboard_view
from views import blueprint_view
from views import boq_view
from views import billing_view
from views import ai_assistant_view
from views import forecasting_view
from views import collaboration_view
from views import settings_view
from views import profit_calculator_view
from views import compare_view
from views import structural_calc_view
from views import gantt_view
from views import ipc_view
from views import suppliers_view
from views import qaqc_view
from views import admin_view
from views import mep_view
from views import tender_hub_view
from views import fidic_scanner_view
from views import bbs_view
from views import survey_view
from views import drawing_engine_view
from views import hr_view
from views import inventory_view
from views import assets_view
from views import finance_view
from views import legal_view
from views import ai_brain_view
from views import fidic_letters_view
from views import workspace_view
