from . import auth_view
from . import dashboard_view
from . import blueprint_view
from . import boq_view
from . import billing_view
from . import ai_assistant_view
from . import forecasting_view
from . import collaboration_view
from . import settings_view
from . import profit_calculator_view
from . import compare_view
from . import structural_calc_view
from . import gantt_view
from . import ipc_view
from . import suppliers_view
from . import qaqc_view
from . import admin_view
from . import mep_view
from . import tender_hub_view
from . import fidic_scanner_view
from . import bbs_view
from . import survey_view
from . import drawing_engine_view
from . import hr_view
from . import inventory_view
from . import assets_view
from . import finance_view
from . import legal_view
from . import ai_brain_view
from . import fidic_letters_view
from . import workspace_view
