import io
import tempfile
import os
from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF

# Force register a default font to avoid errors on basic systems, ideally Arabic font
try:
    pdfmetrics.registerFont(TTFont('Tahoma', 'tahoma.ttf'))
    DEFAULT_FONT = 'Tahoma'
except Exception:
    DEFAULT_FONT = 'Helvetica'

def generate_pdf_report(svg_text: str, project_data: dict, project_type:str, finishings: str = "") -> bytes:
    """Generates a professional A4 landscape PDF containing the SVG and project metadata."""
    buffer = io.BytesIO()
    
    # Create the PDF Canvas
    c = canvas.Canvas(buffer, pagesize=landscape(A4))
    width, height = landscape(A4)
    
    c.setTitle(f"EngiCost AI - {project_data.get('project_title', 'Blueprint')}")
    
    # ─── 1. Draw Title Block / Border ──────────────
    c.setLineWidth(2)
    c.setStrokeColor(colors.HexColor("#1e293b"))
    c.rect(20, 20, width - 40, height - 40)
    
    # Header Line
    c.line(20, height - 80, width - 20, height - 80)
    
    # Side Info Box Line
    info_width = 250
    c.line(width - 20 - info_width, 20, width - 20 - info_width, height - 80)
    
    # ─── 2. Header Content ────────────────────────
    c.setFont(DEFAULT_FONT, 24)
    c.setFillColor(colors.HexColor("#0ea5e9"))
    c.drawString(40, height - 60, "EngiCost AI - Professional BIM Plan")
    
    c.setFont(DEFAULT_FONT, 14)
    c.setFillColor(colors.HexColor("#64748b"))
    c.drawRightString(width - 40, height - 60, "V1.7.5 Pro | AI-Generated Blueprint")
    
    # ─── 3. Project Metadata (Right Panel) ────────
    panel_x = width - 20 - info_width + 20
    text_y = height - 120
    
    c.setFont(DEFAULT_FONT, 16)
    c.setFillColor(colors.HexColor("#0f172a"))
    c.drawString(panel_x, text_y, "PROJECT INFO")
    c.line(panel_x, text_y - 5, panel_x + info_width - 40, text_y - 5)
    
    text_y -= 40
    c.setFont(DEFAULT_FONT, 12)
    details = [
        f"Title: {project_data.get('project_title', 'Custom Plan')}",
        f"Type: {project_type.capitalize()}",
        f"Style: {project_data.get('style', 'Modern')}",
        f"Floors: {project_data.get('floors', 1)}",
        f"Layout Built: {len(project_data.get('rooms', []))} Rooms",
    ]
    
    for line in details:
        c.drawString(panel_x, text_y, line)
        text_y -= 25
        
    # Analysis Summary
    calc_area = sum([(w.get('w',0)*w.get('h',0))/10000 for w in project_data.get('walls', [])])
    if calc_area < 10: calc_area = 150 # Fallback
    
    text_y -= 20
    c.setFont(DEFAULT_FONT, 16)
    c.drawString(panel_x, text_y, "ENGINEERING DATA")
    c.line(panel_x, text_y - 5, panel_x + info_width - 40, text_y - 5)
    
    text_y -= 40
    c.setFont(DEFAULT_FONT, 12)
    c.drawString(panel_x, text_y, f"Est. Footprint: {calc_area:.2f} m2")
    c.drawString(panel_x, text_y - 25, f"Components: {len(project_data.get('walls', [])) + len(project_data.get('openings', []))}")
    
    # Stamp / Signature
    stamp_y = 60
    c.setFont(DEFAULT_FONT, 10)
    c.setFillColor(colors.HexColor("#94a3b8"))
    c.drawString(panel_x, stamp_y + 20, "AUTO-GENERATED BY ENGICOST AI")
    c.drawString(panel_x, stamp_y, "Not for final construction without review.")
    
    # ─── 4. Render SVG into the Left Area ─────────
    try:
        # Save SVG text to a temp file because svglib reads from files
        with tempfile.NamedTemporaryFile(delete=False, suffix=".svg", mode="w", encoding="utf-8") as tmp:
            tmp.write(svg_text)
            tmp_path = tmp.name

        # Read into ReportLab Drawing
        drawing = svg2rlg(tmp_path)
        
        # Calculate scaling to fit into the left drawing area
        drawing_area_w = width - 40 - info_width
        drawing_area_h = height - 100 - 20
        
        scale_w = (drawing_area_w - 40) / drawing.width
        scale_h = (drawing_area_h - 40) / drawing.height
        scale = min(scale_w, scale_h)
        
        drawing.scale(scale, scale)
        drawing.width *= scale
        drawing.height *= scale
        
        # Center drawing within the area
        draw_x = 20 + (drawing_area_w - drawing.width) / 2
        draw_y = 20 + (drawing_area_h - drawing.height) / 2
        
        renderPDF.draw(drawing, c, draw_x, draw_y)
        
        os.remove(tmp_path)
        
    except Exception as e:
        c.setFont(DEFAULT_FONT, 14)
        c.setFillColor(colors.red)
        c.drawString(40, height / 2, f"Error rendering SVG: {e}")

    # Finalize
    c.showPage()
    
    # Option 2: Details Page if finishings exist
    if finishings:
        c.setFont(DEFAULT_FONT, 20)
        c.setFillColor(colors.HexColor("#0ea5e9"))
        c.drawString(40, height - 60, "Project Concept & Finishes")
        c.line(40, height - 70, width - 40, height - 70)
        
        c.setFont(DEFAULT_FONT, 12)
        c.setFillColor(colors.black)
        
        t = c.beginText(40, height - 100)
        # Handle word wrap roughly
        for line in finishings.split("\n"):
            t.textLine(line[:120])
        c.drawText(t)
        
        c.showPage()

    c.save()
    
    return buffer.getvalue()
